version: "2"
run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errchkjson
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - prealloc
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - exhaustive
    - exhaustruct
    - paralleltest
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*github.com/spf13/pflag.FlagSet).GetString
        - (*github.com/fatih/color.Color).Println
        - (io.Closer).Close
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 30
    goconst:
      min-len: 3
      min-occurrences: 15
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nestif:
      min-complexity: 5
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
        path: cmd/.*main\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
