// ABOUTME: Protocol buffer definitions for agent-server communication.
// ABOUTME: Defines the bidirectional streaming protocol for coven control.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: coven.proto

package coven

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CovenControl_AgentStream_FullMethodName = "/coven.CovenControl/AgentStream"
)

// CovenControlClient is the client API for CovenControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent connects to server, receives commands, sends results
type CovenControlClient interface {
	// Agent registration - bidirectional stream for lifecycle
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type covenControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCovenControlClient(cc grpc.ClientConnInterface) CovenControlClient {
	return &covenControlClient{cc}
}

func (c *covenControlClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CovenControl_ServiceDesc.Streams[0], CovenControl_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CovenControl_AgentStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// CovenControlServer is the server API for CovenControl service.
// All implementations must embed UnimplementedCovenControlServer
// for forward compatibility.
//
// Agent connects to server, receives commands, sends results
type CovenControlServer interface {
	// Agent registration - bidirectional stream for lifecycle
	AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedCovenControlServer()
}

// UnimplementedCovenControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCovenControlServer struct{}

func (UnimplementedCovenControlServer) AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedCovenControlServer) mustEmbedUnimplementedCovenControlServer() {}
func (UnimplementedCovenControlServer) testEmbeddedByValue()                      {}

// UnsafeCovenControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CovenControlServer will
// result in compilation errors.
type UnsafeCovenControlServer interface {
	mustEmbedUnimplementedCovenControlServer()
}

func RegisterCovenControlServer(s grpc.ServiceRegistrar, srv CovenControlServer) {
	// If the following call panics, it indicates UnimplementedCovenControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CovenControl_ServiceDesc, srv)
}

func _CovenControl_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CovenControlServer).AgentStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CovenControl_AgentStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// CovenControl_ServiceDesc is the grpc.ServiceDesc for CovenControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CovenControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coven.CovenControl",
	HandlerType: (*CovenControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _CovenControl_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "coven.proto",
}

const (
	AdminService_ListBindings_FullMethodName    = "/coven.AdminService/ListBindings"
	AdminService_CreateBinding_FullMethodName   = "/coven.AdminService/CreateBinding"
	AdminService_UpdateBinding_FullMethodName   = "/coven.AdminService/UpdateBinding"
	AdminService_DeleteBinding_FullMethodName   = "/coven.AdminService/DeleteBinding"
	AdminService_CreateToken_FullMethodName     = "/coven.AdminService/CreateToken"
	AdminService_ListPrincipals_FullMethodName  = "/coven.AdminService/ListPrincipals"
	AdminService_CreatePrincipal_FullMethodName = "/coven.AdminService/CreatePrincipal"
	AdminService_DeletePrincipal_FullMethodName = "/coven.AdminService/DeletePrincipal"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides administrative operations for managing the gateway.
// All methods require admin or owner role (enforced by RequireAdmin interceptor).
type AdminServiceClient interface {
	ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error)
	CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*Binding, error)
	UpdateBinding(ctx context.Context, in *UpdateBindingRequest, opts ...grpc.CallOption) (*Binding, error)
	DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error)
	// Token management
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error)
	// Principal management
	ListPrincipals(ctx context.Context, in *ListPrincipalsRequest, opts ...grpc.CallOption) (*ListPrincipalsResponse, error)
	CreatePrincipal(ctx context.Context, in *CreatePrincipalRequest, opts ...grpc.CallOption) (*Principal, error)
	DeletePrincipal(ctx context.Context, in *DeletePrincipalRequest, opts ...grpc.CallOption) (*DeletePrincipalResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBindingsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*Binding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Binding)
	err := c.cc.Invoke(ctx, AdminService_CreateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateBinding(ctx context.Context, in *UpdateBindingRequest, opts ...grpc.CallOption) (*Binding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Binding)
	err := c.cc.Invoke(ctx, AdminService_UpdateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBindingResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTokenResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPrincipals(ctx context.Context, in *ListPrincipalsRequest, opts ...grpc.CallOption) (*ListPrincipalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPrincipalsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListPrincipals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreatePrincipal(ctx context.Context, in *CreatePrincipalRequest, opts ...grpc.CallOption) (*Principal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Principal)
	err := c.cc.Invoke(ctx, AdminService_CreatePrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeletePrincipal(ctx context.Context, in *DeletePrincipalRequest, opts ...grpc.CallOption) (*DeletePrincipalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePrincipalResponse)
	err := c.cc.Invoke(ctx, AdminService_DeletePrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides administrative operations for managing the gateway.
// All methods require admin or owner role (enforced by RequireAdmin interceptor).
type AdminServiceServer interface {
	ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error)
	CreateBinding(context.Context, *CreateBindingRequest) (*Binding, error)
	UpdateBinding(context.Context, *UpdateBindingRequest) (*Binding, error)
	DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error)
	// Token management
	CreateToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error)
	// Principal management
	ListPrincipals(context.Context, *ListPrincipalsRequest) (*ListPrincipalsResponse, error)
	CreatePrincipal(context.Context, *CreatePrincipalRequest) (*Principal, error)
	DeletePrincipal(context.Context, *DeletePrincipalRequest) (*DeletePrincipalResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBindings not implemented")
}
func (UnimplementedAdminServiceServer) CreateBinding(context.Context, *CreateBindingRequest) (*Binding, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBinding not implemented")
}
func (UnimplementedAdminServiceServer) UpdateBinding(context.Context, *UpdateBindingRequest) (*Binding, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBinding not implemented")
}
func (UnimplementedAdminServiceServer) DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBinding not implemented")
}
func (UnimplementedAdminServiceServer) CreateToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedAdminServiceServer) ListPrincipals(context.Context, *ListPrincipalsRequest) (*ListPrincipalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrincipals not implemented")
}
func (UnimplementedAdminServiceServer) CreatePrincipal(context.Context, *CreatePrincipalRequest) (*Principal, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrincipal not implemented")
}
func (UnimplementedAdminServiceServer) DeletePrincipal(context.Context, *DeletePrincipalRequest) (*DeletePrincipalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePrincipal not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListBindings(ctx, req.(*ListBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateBinding(ctx, req.(*CreateBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateBinding(ctx, req.(*UpdateBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteBinding(ctx, req.(*DeleteBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPrincipals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrincipalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPrincipals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPrincipals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPrincipals(ctx, req.(*ListPrincipalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreatePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreatePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreatePrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreatePrincipal(ctx, req.(*CreatePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeletePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeletePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeletePrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeletePrincipal(ctx, req.(*DeletePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coven.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBindings",
			Handler:    _AdminService_ListBindings_Handler,
		},
		{
			MethodName: "CreateBinding",
			Handler:    _AdminService_CreateBinding_Handler,
		},
		{
			MethodName: "UpdateBinding",
			Handler:    _AdminService_UpdateBinding_Handler,
		},
		{
			MethodName: "DeleteBinding",
			Handler:    _AdminService_DeleteBinding_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _AdminService_CreateToken_Handler,
		},
		{
			MethodName: "ListPrincipals",
			Handler:    _AdminService_ListPrincipals_Handler,
		},
		{
			MethodName: "CreatePrincipal",
			Handler:    _AdminService_CreatePrincipal_Handler,
		},
		{
			MethodName: "DeletePrincipal",
			Handler:    _AdminService_DeletePrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coven.proto",
}

const (
	ClientService_GetEvents_FullMethodName    = "/coven.ClientService/GetEvents"
	ClientService_GetMe_FullMethodName        = "/coven.ClientService/GetMe"
	ClientService_SendMessage_FullMethodName  = "/coven.ClientService/SendMessage"
	ClientService_StreamEvents_FullMethodName = "/coven.ClientService/StreamEvents"
	ClientService_ListAgents_FullMethodName   = "/coven.ClientService/ListAgents"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientService provides client-facing operations for interacting with agents.
// Requires authenticated principal (member role or higher).
type ClientServiceClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MeResponse, error)
	SendMessage(ctx context.Context, in *ClientSendMessageRequest, opts ...grpc.CallOption) (*ClientSendMessageResponse, error)
	// Real-time streaming of events for a conversation
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientStreamEvent], error)
	// List available agents for this principal
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, ClientService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResponse)
	err := c.cc.Invoke(ctx, ClientService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) SendMessage(ctx context.Context, in *ClientSendMessageRequest, opts ...grpc.CallOption) (*ClientSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientSendMessageResponse)
	err := c.cc.Invoke(ctx, ClientService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[0], ClientService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, ClientStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_StreamEventsClient = grpc.ServerStreamingClient[ClientStreamEvent]

func (c *clientServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, ClientService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
//
// ClientService provides client-facing operations for interacting with agents.
// Requires authenticated principal (member role or higher).
type ClientServiceServer interface {
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	GetMe(context.Context, *emptypb.Empty) (*MeResponse, error)
	SendMessage(context.Context, *ClientSendMessageRequest) (*ClientSendMessageResponse, error)
	// Real-time streaming of events for a conversation
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ClientStreamEvent]) error
	// List available agents for this principal
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedClientServiceServer) GetMe(context.Context, *emptypb.Empty) (*MeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedClientServiceServer) SendMessage(context.Context, *ClientSendMessageRequest) (*ClientSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedClientServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ClientStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedClientServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call panics, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetMe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).SendMessage(ctx, req.(*ClientSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, ClientStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientService_StreamEventsServer = grpc.ServerStreamingServer[ClientStreamEvent]

func _ClientService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coven.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _ClientService_GetEvents_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _ClientService_GetMe_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ClientService_SendMessage_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _ClientService_ListAgents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _ClientService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coven.proto",
}

const (
	PackService_Register_FullMethodName   = "/coven.PackService/Register"
	PackService_ToolResult_FullMethodName = "/coven.PackService/ToolResult"
)

// PackServiceClient is the client API for PackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PackService allows tool packs to connect and provide tools to agents
type PackServiceClient interface {
	// Pack registers with manifest, receives tool execution requests
	Register(ctx context.Context, in *PackManifest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolRequest], error)
	// Pack sends tool execution results back
	ToolResult(ctx context.Context, in *ExecuteToolResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type packServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackServiceClient(cc grpc.ClientConnInterface) PackServiceClient {
	return &packServiceClient{cc}
}

func (c *packServiceClient) Register(ctx context.Context, in *PackManifest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteToolRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackService_ServiceDesc.Streams[0], PackService_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackManifest, ExecuteToolRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackService_RegisterClient = grpc.ServerStreamingClient[ExecuteToolRequest]

func (c *packServiceClient) ToolResult(ctx context.Context, in *ExecuteToolResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PackService_ToolResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackServiceServer is the server API for PackService service.
// All implementations must embed UnimplementedPackServiceServer
// for forward compatibility.
//
// PackService allows tool packs to connect and provide tools to agents
type PackServiceServer interface {
	// Pack registers with manifest, receives tool execution requests
	Register(*PackManifest, grpc.ServerStreamingServer[ExecuteToolRequest]) error
	// Pack sends tool execution results back
	ToolResult(context.Context, *ExecuteToolResponse) (*emptypb.Empty, error)
	mustEmbedUnimplementedPackServiceServer()
}

// UnimplementedPackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackServiceServer struct{}

func (UnimplementedPackServiceServer) Register(*PackManifest, grpc.ServerStreamingServer[ExecuteToolRequest]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPackServiceServer) ToolResult(context.Context, *ExecuteToolResponse) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ToolResult not implemented")
}
func (UnimplementedPackServiceServer) mustEmbedUnimplementedPackServiceServer() {}
func (UnimplementedPackServiceServer) testEmbeddedByValue()                     {}

// UnsafePackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackServiceServer will
// result in compilation errors.
type UnsafePackServiceServer interface {
	mustEmbedUnimplementedPackServiceServer()
}

func RegisterPackServiceServer(s grpc.ServiceRegistrar, srv PackServiceServer) {
	// If the following call panics, it indicates UnimplementedPackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackService_ServiceDesc, srv)
}

func _PackService_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackManifest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackServiceServer).Register(m, &grpc.GenericServerStream[PackManifest, ExecuteToolRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackService_RegisterServer = grpc.ServerStreamingServer[ExecuteToolRequest]

func _PackService_ToolResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackServiceServer).ToolResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackService_ToolResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackServiceServer).ToolResult(ctx, req.(*ExecuteToolResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// PackService_ServiceDesc is the grpc.ServiceDesc for PackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coven.PackService",
	HandlerType: (*PackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToolResult",
			Handler:    _PackService_ToolResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _PackService_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coven.proto",
}
