// ABOUTME: Protocol buffer definitions for agent-server communication.
// ABOUTME: Defines the bidirectional streaming protocol for fold control.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: fold.proto

package fold

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoldControl_AgentStream_FullMethodName = "/fold.FoldControl/AgentStream"
)

// FoldControlClient is the client API for FoldControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent connects to server, receives commands, sends results
type FoldControlClient interface {
	// Agent registration - bidirectional stream for lifecycle
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type foldControlClient struct {
	cc grpc.ClientConnInterface
}

func NewFoldControlClient(cc grpc.ClientConnInterface) FoldControlClient {
	return &foldControlClient{cc}
}

func (c *foldControlClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FoldControl_ServiceDesc.Streams[0], FoldControl_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FoldControl_AgentStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// FoldControlServer is the server API for FoldControl service.
// All implementations must embed UnimplementedFoldControlServer
// for forward compatibility.
//
// Agent connects to server, receives commands, sends results
type FoldControlServer interface {
	// Agent registration - bidirectional stream for lifecycle
	AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedFoldControlServer()
}

// UnimplementedFoldControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoldControlServer struct{}

func (UnimplementedFoldControlServer) AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedFoldControlServer) mustEmbedUnimplementedFoldControlServer() {}
func (UnimplementedFoldControlServer) testEmbeddedByValue()                     {}

// UnsafeFoldControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoldControlServer will
// result in compilation errors.
type UnsafeFoldControlServer interface {
	mustEmbedUnimplementedFoldControlServer()
}

func RegisterFoldControlServer(s grpc.ServiceRegistrar, srv FoldControlServer) {
	// If the following call panics, it indicates UnimplementedFoldControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoldControl_ServiceDesc, srv)
}

func _FoldControl_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FoldControlServer).AgentStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FoldControl_AgentStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// FoldControl_ServiceDesc is the grpc.ServiceDesc for FoldControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoldControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fold.FoldControl",
	HandlerType: (*FoldControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _FoldControl_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fold.proto",
}
