// ABOUTME: Protocol buffer definitions for agent-server communication.
// ABOUTME: Defines the bidirectional streaming protocol for fold control.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: fold.proto

package fold

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from agent to server
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Response
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_fold_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetResponse() *MessageResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterAgent `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Response struct {
	Response *MessageResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Response) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

// Git repository state (optional - agent may not be in a git repo)
type GitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Dirty         bool                   `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Remote        string                 `protobuf:"bytes,4,opt,name=remote,proto3" json:"remote,omitempty"`
	Ahead         int32                  `protobuf:"varint,5,opt,name=ahead,proto3" json:"ahead,omitempty"`
	Behind        int32                  `protobuf:"varint,6,opt,name=behind,proto3" json:"behind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitInfo) Reset() {
	*x = GitInfo{}
	mi := &file_fold_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitInfo) ProtoMessage() {}

func (x *GitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitInfo.ProtoReflect.Descriptor instead.
func (*GitInfo) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{1}
}

func (x *GitInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GitInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GitInfo) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *GitInfo) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *GitInfo) GetAhead() int32 {
	if x != nil {
		return x.Ahead
	}
	return 0
}

func (x *GitInfo) GetBehind() int32 {
	if x != nil {
		return x.Behind
	}
	return 0
}

// Environment metadata sent during registration
type AgentMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkingDirectory string                 `protobuf:"bytes,1,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Git              *GitInfo               `protobuf:"bytes,2,opt,name=git,proto3" json:"git,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os               string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_fold_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMetadata) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *AgentMetadata) GetGit() *GitInfo {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *AgentMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// Agent registration
type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Unique agent identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // Human-readable name
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`      // What this agent can do
	Metadata      *AgentMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`              // Environment context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_fold_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgent) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response to a message request
type MessageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Correlates with SendMessage
	// Types that are valid to be assigned to Event:
	//
	//	*MessageResponse_Thinking
	//	*MessageResponse_Text
	//	*MessageResponse_ToolUse
	//	*MessageResponse_ToolResult
	//	*MessageResponse_Done
	//	*MessageResponse_Error
	//	*MessageResponse_File
	//	*MessageResponse_ToolApprovalRequest
	Event         isMessageResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_fold_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{4}
}

func (x *MessageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MessageResponse) GetEvent() isMessageResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MessageResponse) GetThinking() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Thinking); ok {
			return x.Thinking
		}
	}
	return ""
}

func (x *MessageResponse) GetText() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MessageResponse) GetToolUse() *ToolUse {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_ToolUse); ok {
			return x.ToolUse
		}
	}
	return nil
}

func (x *MessageResponse) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *MessageResponse) GetDone() *Done {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *MessageResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *MessageResponse) GetFile() *FileData {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *MessageResponse) GetToolApprovalRequest() *ToolApprovalRequest {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_ToolApprovalRequest); ok {
			return x.ToolApprovalRequest
		}
	}
	return nil
}

type isMessageResponse_Event interface {
	isMessageResponse_Event()
}

type MessageResponse_Thinking struct {
	Thinking string `protobuf:"bytes,2,opt,name=thinking,proto3,oneof"`
}

type MessageResponse_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type MessageResponse_ToolUse struct {
	ToolUse *ToolUse `protobuf:"bytes,4,opt,name=tool_use,json=toolUse,proto3,oneof"`
}

type MessageResponse_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type MessageResponse_Done struct {
	Done *Done `protobuf:"bytes,6,opt,name=done,proto3,oneof"`
}

type MessageResponse_Error struct {
	Error string `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type MessageResponse_File struct {
	File *FileData `protobuf:"bytes,8,opt,name=file,proto3,oneof"`
}

type MessageResponse_ToolApprovalRequest struct {
	ToolApprovalRequest *ToolApprovalRequest `protobuf:"bytes,9,opt,name=tool_approval_request,json=toolApprovalRequest,proto3,oneof"`
}

func (*MessageResponse_Thinking) isMessageResponse_Event() {}

func (*MessageResponse_Text) isMessageResponse_Event() {}

func (*MessageResponse_ToolUse) isMessageResponse_Event() {}

func (*MessageResponse_ToolResult) isMessageResponse_Event() {}

func (*MessageResponse_Done) isMessageResponse_Event() {}

func (*MessageResponse_Error) isMessageResponse_Event() {}

func (*MessageResponse_File) isMessageResponse_Event() {}

func (*MessageResponse_ToolApprovalRequest) isMessageResponse_Event() {}

// Request for tool approval before execution (agent → server)
type ToolApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Correlates with ToolUse.id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // Tool name
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // Tool input for display
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolApprovalRequest) Reset() {
	*x = ToolApprovalRequest{}
	mi := &file_fold_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolApprovalRequest) ProtoMessage() {}

func (x *ToolApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolApprovalRequest.ProtoReflect.Descriptor instead.
func (*ToolApprovalRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{5}
}

func (x *ToolApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolApprovalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolApprovalRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_fold_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{6}
}

func (x *ToolUse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_fold_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullResponse  string                 `protobuf:"bytes,1,opt,name=full_response,json=fullResponse,proto3" json:"full_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_fold_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{8}
}

func (x *Done) GetFullResponse() string {
	if x != nil {
		return x.FullResponse
	}
	return ""
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_fold_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{9}
}

func (x *FileData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileData) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_fold_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// Messages from server to agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_SendMessage
	//	*ServerMessage_Shutdown
	//	*ServerMessage_ToolApproval
	//	*ServerMessage_RegistrationError
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_fold_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{11}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ServerMessage) GetToolApproval() *ToolApprovalResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ToolApproval); ok {
			return x.ToolApproval
		}
	}
	return nil
}

func (x *ServerMessage) GetRegistrationError() *RegistrationError {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegistrationError); ok {
			return x.RegistrationError
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ServerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type ServerMessage_ToolApproval struct {
	ToolApproval *ToolApprovalResponse `protobuf:"bytes,4,opt,name=tool_approval,json=toolApproval,proto3,oneof"`
}

type ServerMessage_RegistrationError struct {
	RegistrationError *RegistrationError `protobuf:"bytes,5,opt,name=registration_error,json=registrationError,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Payload() {}

func (*ServerMessage_SendMessage) isServerMessage_Payload() {}

func (*ServerMessage_Shutdown) isServerMessage_Payload() {}

func (*ServerMessage_ToolApproval) isServerMessage_Payload() {}

func (*ServerMessage_RegistrationError) isServerMessage_Payload() {}

// Server rejects registration (e.g., agent_id already taken)
type RegistrationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`                              // Human-readable error message
	SuggestedId   string                 `protobuf:"bytes,2,opt,name=suggested_id,json=suggestedId,proto3" json:"suggested_id,omitempty"` // Optional: server-suggested alternative ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationError) Reset() {
	*x = RegistrationError{}
	mi := &file_fold_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationError) ProtoMessage() {}

func (x *RegistrationError) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationError.ProtoReflect.Descriptor instead.
func (*RegistrationError) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{12}
}

func (x *RegistrationError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegistrationError) GetSuggestedId() string {
	if x != nil {
		return x.SuggestedId
	}
	return ""
}

// Response to tool approval request (server → agent)
type ToolApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // Correlates with ToolApprovalRequest.id
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`                       // True = execute, False = skip
	ApproveAll    bool                   `protobuf:"varint,3,opt,name=approve_all,json=approveAll,proto3" json:"approve_all,omitempty"` // If true, auto-approve remaining tools this request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolApprovalResponse) Reset() {
	*x = ToolApprovalResponse{}
	mi := &file_fold_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolApprovalResponse) ProtoMessage() {}

func (x *ToolApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolApprovalResponse.ProtoReflect.Descriptor instead.
func (*ToolApprovalResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{13}
}

func (x *ToolApprovalResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolApprovalResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ToolApprovalResponse) GetApproveAll() bool {
	if x != nil {
		return x.ApproveAll
	}
	return false
}

// Server acknowledges registration
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Confirmed agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_fold_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{14}
}

func (x *Welcome) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Welcome) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Server tells agent to process a message
type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique request ID for correlation
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // Conversation thread
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`                        // Who sent the message
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                      // Message content
	Attachments   []*FileAttachment      `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_fold_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{15}
}

func (x *SendMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessage) GetAttachments() []*FileAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type FileAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	mi := &file_fold_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{16}
}

func (x *FileAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileAttachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Server tells agent to shut down
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_fold_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{17}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Binding represents a channel-to-agent mapping for message routing
type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Frontend      string                 `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO-8601
	CreatedBy     *string                `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_fold_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{18}
}

func (x *Binding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Binding) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *Binding) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Binding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Binding) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Binding) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

type ListBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      *string                `protobuf:"bytes,1,opt,name=frontend,proto3,oneof" json:"frontend,omitempty"`
	AgentId       *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsRequest) Reset() {
	*x = ListBindingsRequest{}
	mi := &file_fold_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsRequest) ProtoMessage() {}

func (x *ListBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListBindingsRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{19}
}

func (x *ListBindingsRequest) GetFrontend() string {
	if x != nil && x.Frontend != nil {
		return *x.Frontend
	}
	return ""
}

func (x *ListBindingsRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type ListBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*Binding             `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsResponse) Reset() {
	*x = ListBindingsResponse{}
	mi := &file_fold_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsResponse) ProtoMessage() {}

func (x *ListBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListBindingsResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{20}
}

func (x *ListBindingsResponse) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type CreateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      string                 `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingRequest) Reset() {
	*x = CreateBindingRequest{}
	mi := &file_fold_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingRequest) ProtoMessage() {}

func (x *CreateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{21}
}

func (x *CreateBindingRequest) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *CreateBindingRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateBindingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UpdateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBindingRequest) Reset() {
	*x = UpdateBindingRequest{}
	mi := &file_fold_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindingRequest) ProtoMessage() {}

func (x *UpdateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBindingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingRequest) Reset() {
	*x = DeleteBindingRequest{}
	mi := &file_fold_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingRequest) ProtoMessage() {}

func (x *DeleteBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingResponse) Reset() {
	*x = DeleteBindingResponse{}
	mi := &file_fold_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingResponse) ProtoMessage() {}

func (x *DeleteBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBindingResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{24}
}

// Token management messages
type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"` // Principal to create token for
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`   // Token lifetime in seconds (default: 30 days)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_fold_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{25}
}

func (x *CreateTokenRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CreateTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // The generated JWT token
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // ISO-8601 expiration timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_fold_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{26}
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// Principal management messages
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "client", "agent", "pack"
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                           // "pending", "approved", "online", "offline", "revoked"
	PubkeyFp      *string                `protobuf:"bytes,5,opt,name=pubkey_fp,json=pubkeyFp,proto3,oneof" json:"pubkey_fp,omitempty"` // SSH public key fingerprint (for agents)
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // ISO-8601
	Roles         []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_fold_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{27}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Principal) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Principal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Principal) GetPubkeyFp() string {
	if x != nil && x.PubkeyFp != nil {
		return *x.PubkeyFp
	}
	return ""
}

func (x *Principal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Principal) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListPrincipalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`     // Filter by type
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"` // Filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrincipalsRequest) Reset() {
	*x = ListPrincipalsRequest{}
	mi := &file_fold_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrincipalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrincipalsRequest) ProtoMessage() {}

func (x *ListPrincipalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrincipalsRequest.ProtoReflect.Descriptor instead.
func (*ListPrincipalsRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{28}
}

func (x *ListPrincipalsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListPrincipalsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ListPrincipalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principals    []*Principal           `protobuf:"bytes,1,rep,name=principals,proto3" json:"principals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrincipalsResponse) Reset() {
	*x = ListPrincipalsResponse{}
	mi := &file_fold_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrincipalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrincipalsResponse) ProtoMessage() {}

func (x *ListPrincipalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrincipalsResponse.ProtoReflect.Descriptor instead.
func (*ListPrincipalsResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{29}
}

func (x *ListPrincipalsResponse) GetPrincipals() []*Principal {
	if x != nil {
		return x.Principals
	}
	return nil
}

type CreatePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "client" or "agent"
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Pubkey        *string                `protobuf:"bytes,3,opt,name=pubkey,proto3,oneof" json:"pubkey,omitempty"`                     // Full SSH public key (for agents)
	PubkeyFp      *string                `protobuf:"bytes,4,opt,name=pubkey_fp,json=pubkeyFp,proto3,oneof" json:"pubkey_fp,omitempty"` // Or just the fingerprint
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`                             // Roles to assign (e.g., "member")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrincipalRequest) Reset() {
	*x = CreatePrincipalRequest{}
	mi := &file_fold_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrincipalRequest) ProtoMessage() {}

func (x *CreatePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrincipalRequest.ProtoReflect.Descriptor instead.
func (*CreatePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{30}
}

func (x *CreatePrincipalRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePrincipalRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreatePrincipalRequest) GetPubkey() string {
	if x != nil && x.Pubkey != nil {
		return *x.Pubkey
	}
	return ""
}

func (x *CreatePrincipalRequest) GetPubkeyFp() string {
	if x != nil && x.PubkeyFp != nil {
		return *x.PubkeyFp
	}
	return ""
}

func (x *CreatePrincipalRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type DeletePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalRequest) Reset() {
	*x = DeletePrincipalRequest{}
	mi := &file_fold_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalRequest) ProtoMessage() {}

func (x *DeletePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalRequest.ProtoReflect.Descriptor instead.
func (*DeletePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{31}
}

func (x *DeletePrincipalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrincipalResponse) Reset() {
	*x = DeletePrincipalResponse{}
	mi := &file_fold_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrincipalResponse) ProtoMessage() {}

func (x *DeletePrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrincipalResponse.ProtoReflect.Descriptor instead.
func (*DeletePrincipalResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{32}
}

// ClientSendMessageRequest is the request for direct client message sending.
// The idempotency_key is required and must be unique per message to prevent duplicates.
type ClientSendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationKey string                 `protobuf:"bytes,1,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Attachments     []*FileAttachment      `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // required, 1-100 chars
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientSendMessageRequest) Reset() {
	*x = ClientSendMessageRequest{}
	mi := &file_fold_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSendMessageRequest) ProtoMessage() {}

func (x *ClientSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSendMessageRequest.ProtoReflect.Descriptor instead.
func (*ClientSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{33}
}

func (x *ClientSendMessageRequest) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

func (x *ClientSendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClientSendMessageRequest) GetAttachments() []*FileAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ClientSendMessageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// ClientSendMessageResponse is the response for direct client message sending.
type ClientSendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                        // "accepted" or "duplicate"
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // assigned message ID (empty for duplicates)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSendMessageResponse) Reset() {
	*x = ClientSendMessageResponse{}
	mi := &file_fold_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSendMessageResponse) ProtoMessage() {}

func (x *ClientSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSendMessageResponse.ProtoReflect.Descriptor instead.
func (*ClientSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{34}
}

func (x *ClientSendMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClientSendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// MeResponse contains the authenticated principal's identity information
type MeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId       string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	PrincipalType     string                 `protobuf:"bytes,2,opt,name=principal_type,json=principalType,proto3" json:"principal_type,omitempty"`
	DisplayName       string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Roles             []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	MemberId          *string                `protobuf:"bytes,6,opt,name=member_id,json=memberId,proto3,oneof" json:"member_id,omitempty"`
	MemberDisplayName *string                `protobuf:"bytes,7,opt,name=member_display_name,json=memberDisplayName,proto3,oneof" json:"member_display_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_fold_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{35}
}

func (x *MeResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *MeResponse) GetPrincipalType() string {
	if x != nil {
		return x.PrincipalType
	}
	return ""
}

func (x *MeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MeResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MeResponse) GetMemberId() string {
	if x != nil && x.MemberId != nil {
		return *x.MemberId
	}
	return ""
}

func (x *MeResponse) GetMemberDisplayName() string {
	if x != nil && x.MemberDisplayName != nil {
		return *x.MemberDisplayName
	}
	return ""
}

// Event represents a ledger event in conversation history
type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationKey  string                 `protobuf:"bytes,2,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"`
	Direction        string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // "inbound_to_agent" or "outbound_from_agent"
	Author           string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Timestamp        string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO-8601
	Type             string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`           // "message", "tool_call", "tool_result", "system", "error"
	Text             *string                `protobuf:"bytes,7,opt,name=text,proto3,oneof" json:"text,omitempty"`
	RawTransport     *string                `protobuf:"bytes,8,opt,name=raw_transport,json=rawTransport,proto3,oneof" json:"raw_transport,omitempty"`
	RawPayloadRef    *string                `protobuf:"bytes,9,opt,name=raw_payload_ref,json=rawPayloadRef,proto3,oneof" json:"raw_payload_ref,omitempty"`
	ActorPrincipalId *string                `protobuf:"bytes,10,opt,name=actor_principal_id,json=actorPrincipalId,proto3,oneof" json:"actor_principal_id,omitempty"`
	ActorMemberId    *string                `protobuf:"bytes,11,opt,name=actor_member_id,json=actorMemberId,proto3,oneof" json:"actor_member_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_fold_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{36}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

func (x *Event) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Event) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Event) GetRawTransport() string {
	if x != nil && x.RawTransport != nil {
		return *x.RawTransport
	}
	return ""
}

func (x *Event) GetRawPayloadRef() string {
	if x != nil && x.RawPayloadRef != nil {
		return *x.RawPayloadRef
	}
	return ""
}

func (x *Event) GetActorPrincipalId() string {
	if x != nil && x.ActorPrincipalId != nil {
		return *x.ActorPrincipalId
	}
	return ""
}

func (x *Event) GetActorMemberId() string {
	if x != nil && x.ActorMemberId != nil {
		return *x.ActorMemberId
	}
	return ""
}

type GetEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationKey string                 `protobuf:"bytes,1,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"`
	Since           *string                `protobuf:"bytes,2,opt,name=since,proto3,oneof" json:"since,omitempty"`  // ISO-8601
	Until           *string                `protobuf:"bytes,3,opt,name=until,proto3,oneof" json:"until,omitempty"`  // ISO-8601
	Limit           *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"` // 1-500
	Cursor          *string                `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_fold_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{37}
}

func (x *GetEventsRequest) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

func (x *GetEventsRequest) GetSince() string {
	if x != nil && x.Since != nil {
		return *x.Since
	}
	return ""
}

func (x *GetEventsRequest) GetUntil() string {
	if x != nil && x.Until != nil {
		return *x.Until
	}
	return ""
}

func (x *GetEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetEventsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_fold_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{38}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *GetEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_fold_proto protoreflect.FileDescriptor

const file_fold_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fold.proto\x12\x04fold\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x01\n" +
	"\fAgentMessage\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.fold.RegisterAgentH\x00R\bregister\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x15.fold.MessageResponseH\x00R\bresponse\x12/\n" +
	"\theartbeat\x18\x03 \x01(\v2\x0f.fold.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x95\x01\n" +
	"\aGitInfo\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x14\n" +
	"\x05dirty\x18\x03 \x01(\bR\x05dirty\x12\x16\n" +
	"\x06remote\x18\x04 \x01(\tR\x06remote\x12\x14\n" +
	"\x05ahead\x18\x05 \x01(\x05R\x05ahead\x12\x16\n" +
	"\x06behind\x18\x06 \x01(\x05R\x06behind\"\x89\x01\n" +
	"\rAgentMetadata\x12+\n" +
	"\x11working_directory\x18\x01 \x01(\tR\x10workingDirectory\x12\x1f\n" +
	"\x03git\x18\x02 \x01(\v2\r.fold.GitInfoR\x03git\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\"\x93\x01\n" +
	"\rRegisterAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12/\n" +
	"\bmetadata\x18\x04 \x01(\v2\x13.fold.AgentMetadataR\bmetadata\"\xff\x02\n" +
	"\x0fMessageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\bthinking\x18\x02 \x01(\tH\x00R\bthinking\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x12*\n" +
	"\btool_use\x18\x04 \x01(\v2\r.fold.ToolUseH\x00R\atoolUse\x123\n" +
	"\vtool_result\x18\x05 \x01(\v2\x10.fold.ToolResultH\x00R\n" +
	"toolResult\x12 \n" +
	"\x04done\x18\x06 \x01(\v2\n" +
	".fold.DoneH\x00R\x04done\x12\x16\n" +
	"\x05error\x18\a \x01(\tH\x00R\x05error\x12$\n" +
	"\x04file\x18\b \x01(\v2\x0e.fold.FileDataH\x00R\x04file\x12O\n" +
	"\x15tool_approval_request\x18\t \x01(\v2\x19.fold.ToolApprovalRequestH\x00R\x13toolApprovalRequestB\a\n" +
	"\x05event\"X\n" +
	"\x13ToolApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\"L\n" +
	"\aToolUse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\"O\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"+\n" +
	"\x04Done\x12#\n" +
	"\rfull_response\x18\x01 \x01(\tR\ffullResponse\"W\n" +
	"\bFileData\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xb8\x02\n" +
	"\rServerMessage\x12)\n" +
	"\awelcome\x18\x01 \x01(\v2\r.fold.WelcomeH\x00R\awelcome\x126\n" +
	"\fsend_message\x18\x02 \x01(\v2\x11.fold.SendMessageH\x00R\vsendMessage\x12,\n" +
	"\bshutdown\x18\x03 \x01(\v2\x0e.fold.ShutdownH\x00R\bshutdown\x12A\n" +
	"\rtool_approval\x18\x04 \x01(\v2\x1a.fold.ToolApprovalResponseH\x00R\ftoolApproval\x12H\n" +
	"\x12registration_error\x18\x05 \x01(\v2\x17.fold.RegistrationErrorH\x00R\x11registrationErrorB\t\n" +
	"\apayload\"N\n" +
	"\x11RegistrationError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12!\n" +
	"\fsuggested_id\x18\x02 \x01(\tR\vsuggestedId\"c\n" +
	"\x14ToolApprovalResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1f\n" +
	"\vapprove_all\x18\x03 \x01(\bR\n" +
	"approveAll\"A\n" +
	"\aWelcome\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"\xb3\x01\n" +
	"\vSendMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x126\n" +
	"\vattachments\x18\x05 \x03(\v2\x14.fold.FileAttachmentR\vattachments\"]\n" +
	"\x0eFileAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xc1\x01\n" +
	"\aBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfrontend\x18\x02 \x01(\tR\bfrontend\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tH\x00R\tcreatedBy\x88\x01\x01B\r\n" +
	"\v_created_by\"p\n" +
	"\x13ListBindingsRequest\x12\x1f\n" +
	"\bfrontend\x18\x01 \x01(\tH\x00R\bfrontend\x88\x01\x01\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tH\x01R\aagentId\x88\x01\x01B\v\n" +
	"\t_frontendB\v\n" +
	"\t_agent_id\"A\n" +
	"\x14ListBindingsResponse\x12)\n" +
	"\bbindings\x18\x01 \x03(\v2\r.fold.BindingR\bbindings\"l\n" +
	"\x14CreateBindingRequest\x12\x1a\n" +
	"\bfrontend\x18\x01 \x01(\tR\bfrontend\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"A\n" +
	"\x14UpdateBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"&\n" +
	"\x14DeleteBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteBindingResponse\"X\n" +
	"\x12CreateTokenRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"J\n" +
	"\x13CreateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"\xcf\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\tpubkey_fp\x18\x05 \x01(\tH\x00R\bpubkeyFp\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05rolesB\f\n" +
	"\n" +
	"_pubkey_fp\"a\n" +
	"\x15ListPrincipalsRequest\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01B\a\n" +
	"\x05_typeB\t\n" +
	"\a_status\"I\n" +
	"\x16ListPrincipalsResponse\x12/\n" +
	"\n" +
	"principals\x18\x01 \x03(\v2\x0f.fold.PrincipalR\n" +
	"principals\"\xbd\x01\n" +
	"\x16CreatePrincipalRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\x06pubkey\x18\x03 \x01(\tH\x00R\x06pubkey\x88\x01\x01\x12 \n" +
	"\tpubkey_fp\x18\x04 \x01(\tH\x01R\bpubkeyFp\x88\x01\x01\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05rolesB\t\n" +
	"\a_pubkeyB\f\n" +
	"\n" +
	"_pubkey_fp\"(\n" +
	"\x16DeletePrincipalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeletePrincipalResponse\"\xc0\x01\n" +
	"\x18ClientSendMessageRequest\x12)\n" +
	"\x10conversation_key\x18\x01 \x01(\tR\x0fconversationKey\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x126\n" +
	"\vattachments\x18\x03 \x03(\v2\x14.fold.FileAttachmentR\vattachments\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"R\n" +
	"\x19ClientSendMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\xa4\x02\n" +
	"\n" +
	"MeResponse\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12%\n" +
	"\x0eprincipal_type\x18\x02 \x01(\tR\rprincipalType\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12 \n" +
	"\tmember_id\x18\x06 \x01(\tH\x00R\bmemberId\x88\x01\x01\x123\n" +
	"\x13member_display_name\x18\a \x01(\tH\x01R\x11memberDisplayName\x88\x01\x01B\f\n" +
	"\n" +
	"_member_idB\x16\n" +
	"\x14_member_display_name\"\xd4\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10conversation_key\x18\x02 \x01(\tR\x0fconversationKey\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x17\n" +
	"\x04text\x18\a \x01(\tH\x00R\x04text\x88\x01\x01\x12(\n" +
	"\rraw_transport\x18\b \x01(\tH\x01R\frawTransport\x88\x01\x01\x12+\n" +
	"\x0fraw_payload_ref\x18\t \x01(\tH\x02R\rrawPayloadRef\x88\x01\x01\x121\n" +
	"\x12actor_principal_id\x18\n" +
	" \x01(\tH\x03R\x10actorPrincipalId\x88\x01\x01\x12+\n" +
	"\x0factor_member_id\x18\v \x01(\tH\x04R\ractorMemberId\x88\x01\x01B\a\n" +
	"\x05_textB\x10\n" +
	"\x0e_raw_transportB\x12\n" +
	"\x10_raw_payload_refB\x15\n" +
	"\x13_actor_principal_idB\x12\n" +
	"\x10_actor_member_id\"\xd4\x01\n" +
	"\x10GetEventsRequest\x12)\n" +
	"\x10conversation_key\x18\x01 \x01(\tR\x0fconversationKey\x12\x19\n" +
	"\x05since\x18\x02 \x01(\tH\x00R\x05since\x88\x01\x01\x12\x19\n" +
	"\x05until\x18\x03 \x01(\tH\x01R\x05until\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x05 \x01(\tH\x03R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_sinceB\b\n" +
	"\x06_untilB\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursor\"\x89\x01\n" +
	"\x11GetEventsResponse\x12#\n" +
	"\x06events\x18\x01 \x03(\v2\v.fold.EventR\x06events\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMoreB\x0e\n" +
	"\f_next_cursor2I\n" +
	"\vFoldControl\x12:\n" +
	"\vAgentStream\x12\x12.fold.AgentMessage\x1a\x13.fold.ServerMessage(\x010\x012\xba\x04\n" +
	"\fAdminService\x12E\n" +
	"\fListBindings\x12\x19.fold.ListBindingsRequest\x1a\x1a.fold.ListBindingsResponse\x12:\n" +
	"\rCreateBinding\x12\x1a.fold.CreateBindingRequest\x1a\r.fold.Binding\x12:\n" +
	"\rUpdateBinding\x12\x1a.fold.UpdateBindingRequest\x1a\r.fold.Binding\x12H\n" +
	"\rDeleteBinding\x12\x1a.fold.DeleteBindingRequest\x1a\x1b.fold.DeleteBindingResponse\x12B\n" +
	"\vCreateToken\x12\x18.fold.CreateTokenRequest\x1a\x19.fold.CreateTokenResponse\x12K\n" +
	"\x0eListPrincipals\x12\x1b.fold.ListPrincipalsRequest\x1a\x1c.fold.ListPrincipalsResponse\x12@\n" +
	"\x0fCreatePrincipal\x12\x1c.fold.CreatePrincipalRequest\x1a\x0f.fold.Principal\x12N\n" +
	"\x0fDeletePrincipal\x12\x1c.fold.DeletePrincipalRequest\x1a\x1d.fold.DeletePrincipalResponse2\xd0\x01\n" +
	"\rClientService\x12<\n" +
	"\tGetEvents\x12\x16.fold.GetEventsRequest\x1a\x17.fold.GetEventsResponse\x121\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a\x10.fold.MeResponse\x12N\n" +
	"\vSendMessage\x12\x1e.fold.ClientSendMessageRequest\x1a\x1f.fold.ClientSendMessageResponseb\x06proto3"

var (
	file_fold_proto_rawDescOnce sync.Once
	file_fold_proto_rawDescData []byte
)

func file_fold_proto_rawDescGZIP() []byte {
	file_fold_proto_rawDescOnce.Do(func() {
		file_fold_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fold_proto_rawDesc), len(file_fold_proto_rawDesc)))
	})
	return file_fold_proto_rawDescData
}

var file_fold_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_fold_proto_goTypes = []any{
	(*AgentMessage)(nil),              // 0: fold.AgentMessage
	(*GitInfo)(nil),                   // 1: fold.GitInfo
	(*AgentMetadata)(nil),             // 2: fold.AgentMetadata
	(*RegisterAgent)(nil),             // 3: fold.RegisterAgent
	(*MessageResponse)(nil),           // 4: fold.MessageResponse
	(*ToolApprovalRequest)(nil),       // 5: fold.ToolApprovalRequest
	(*ToolUse)(nil),                   // 6: fold.ToolUse
	(*ToolResult)(nil),                // 7: fold.ToolResult
	(*Done)(nil),                      // 8: fold.Done
	(*FileData)(nil),                  // 9: fold.FileData
	(*Heartbeat)(nil),                 // 10: fold.Heartbeat
	(*ServerMessage)(nil),             // 11: fold.ServerMessage
	(*RegistrationError)(nil),         // 12: fold.RegistrationError
	(*ToolApprovalResponse)(nil),      // 13: fold.ToolApprovalResponse
	(*Welcome)(nil),                   // 14: fold.Welcome
	(*SendMessage)(nil),               // 15: fold.SendMessage
	(*FileAttachment)(nil),            // 16: fold.FileAttachment
	(*Shutdown)(nil),                  // 17: fold.Shutdown
	(*Binding)(nil),                   // 18: fold.Binding
	(*ListBindingsRequest)(nil),       // 19: fold.ListBindingsRequest
	(*ListBindingsResponse)(nil),      // 20: fold.ListBindingsResponse
	(*CreateBindingRequest)(nil),      // 21: fold.CreateBindingRequest
	(*UpdateBindingRequest)(nil),      // 22: fold.UpdateBindingRequest
	(*DeleteBindingRequest)(nil),      // 23: fold.DeleteBindingRequest
	(*DeleteBindingResponse)(nil),     // 24: fold.DeleteBindingResponse
	(*CreateTokenRequest)(nil),        // 25: fold.CreateTokenRequest
	(*CreateTokenResponse)(nil),       // 26: fold.CreateTokenResponse
	(*Principal)(nil),                 // 27: fold.Principal
	(*ListPrincipalsRequest)(nil),     // 28: fold.ListPrincipalsRequest
	(*ListPrincipalsResponse)(nil),    // 29: fold.ListPrincipalsResponse
	(*CreatePrincipalRequest)(nil),    // 30: fold.CreatePrincipalRequest
	(*DeletePrincipalRequest)(nil),    // 31: fold.DeletePrincipalRequest
	(*DeletePrincipalResponse)(nil),   // 32: fold.DeletePrincipalResponse
	(*ClientSendMessageRequest)(nil),  // 33: fold.ClientSendMessageRequest
	(*ClientSendMessageResponse)(nil), // 34: fold.ClientSendMessageResponse
	(*MeResponse)(nil),                // 35: fold.MeResponse
	(*Event)(nil),                     // 36: fold.Event
	(*GetEventsRequest)(nil),          // 37: fold.GetEventsRequest
	(*GetEventsResponse)(nil),         // 38: fold.GetEventsResponse
	(*emptypb.Empty)(nil),             // 39: google.protobuf.Empty
}
var file_fold_proto_depIdxs = []int32{
	3,  // 0: fold.AgentMessage.register:type_name -> fold.RegisterAgent
	4,  // 1: fold.AgentMessage.response:type_name -> fold.MessageResponse
	10, // 2: fold.AgentMessage.heartbeat:type_name -> fold.Heartbeat
	1,  // 3: fold.AgentMetadata.git:type_name -> fold.GitInfo
	2,  // 4: fold.RegisterAgent.metadata:type_name -> fold.AgentMetadata
	6,  // 5: fold.MessageResponse.tool_use:type_name -> fold.ToolUse
	7,  // 6: fold.MessageResponse.tool_result:type_name -> fold.ToolResult
	8,  // 7: fold.MessageResponse.done:type_name -> fold.Done
	9,  // 8: fold.MessageResponse.file:type_name -> fold.FileData
	5,  // 9: fold.MessageResponse.tool_approval_request:type_name -> fold.ToolApprovalRequest
	14, // 10: fold.ServerMessage.welcome:type_name -> fold.Welcome
	15, // 11: fold.ServerMessage.send_message:type_name -> fold.SendMessage
	17, // 12: fold.ServerMessage.shutdown:type_name -> fold.Shutdown
	13, // 13: fold.ServerMessage.tool_approval:type_name -> fold.ToolApprovalResponse
	12, // 14: fold.ServerMessage.registration_error:type_name -> fold.RegistrationError
	16, // 15: fold.SendMessage.attachments:type_name -> fold.FileAttachment
	18, // 16: fold.ListBindingsResponse.bindings:type_name -> fold.Binding
	27, // 17: fold.ListPrincipalsResponse.principals:type_name -> fold.Principal
	16, // 18: fold.ClientSendMessageRequest.attachments:type_name -> fold.FileAttachment
	36, // 19: fold.GetEventsResponse.events:type_name -> fold.Event
	0,  // 20: fold.FoldControl.AgentStream:input_type -> fold.AgentMessage
	19, // 21: fold.AdminService.ListBindings:input_type -> fold.ListBindingsRequest
	21, // 22: fold.AdminService.CreateBinding:input_type -> fold.CreateBindingRequest
	22, // 23: fold.AdminService.UpdateBinding:input_type -> fold.UpdateBindingRequest
	23, // 24: fold.AdminService.DeleteBinding:input_type -> fold.DeleteBindingRequest
	25, // 25: fold.AdminService.CreateToken:input_type -> fold.CreateTokenRequest
	28, // 26: fold.AdminService.ListPrincipals:input_type -> fold.ListPrincipalsRequest
	30, // 27: fold.AdminService.CreatePrincipal:input_type -> fold.CreatePrincipalRequest
	31, // 28: fold.AdminService.DeletePrincipal:input_type -> fold.DeletePrincipalRequest
	37, // 29: fold.ClientService.GetEvents:input_type -> fold.GetEventsRequest
	39, // 30: fold.ClientService.GetMe:input_type -> google.protobuf.Empty
	33, // 31: fold.ClientService.SendMessage:input_type -> fold.ClientSendMessageRequest
	11, // 32: fold.FoldControl.AgentStream:output_type -> fold.ServerMessage
	20, // 33: fold.AdminService.ListBindings:output_type -> fold.ListBindingsResponse
	18, // 34: fold.AdminService.CreateBinding:output_type -> fold.Binding
	18, // 35: fold.AdminService.UpdateBinding:output_type -> fold.Binding
	24, // 36: fold.AdminService.DeleteBinding:output_type -> fold.DeleteBindingResponse
	26, // 37: fold.AdminService.CreateToken:output_type -> fold.CreateTokenResponse
	29, // 38: fold.AdminService.ListPrincipals:output_type -> fold.ListPrincipalsResponse
	27, // 39: fold.AdminService.CreatePrincipal:output_type -> fold.Principal
	32, // 40: fold.AdminService.DeletePrincipal:output_type -> fold.DeletePrincipalResponse
	38, // 41: fold.ClientService.GetEvents:output_type -> fold.GetEventsResponse
	35, // 42: fold.ClientService.GetMe:output_type -> fold.MeResponse
	34, // 43: fold.ClientService.SendMessage:output_type -> fold.ClientSendMessageResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_fold_proto_init() }
func file_fold_proto_init() {
	if File_fold_proto != nil {
		return
	}
	file_fold_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Response)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_fold_proto_msgTypes[4].OneofWrappers = []any{
		(*MessageResponse_Thinking)(nil),
		(*MessageResponse_Text)(nil),
		(*MessageResponse_ToolUse)(nil),
		(*MessageResponse_ToolResult)(nil),
		(*MessageResponse_Done)(nil),
		(*MessageResponse_Error)(nil),
		(*MessageResponse_File)(nil),
		(*MessageResponse_ToolApprovalRequest)(nil),
	}
	file_fold_proto_msgTypes[11].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_SendMessage)(nil),
		(*ServerMessage_Shutdown)(nil),
		(*ServerMessage_ToolApproval)(nil),
		(*ServerMessage_RegistrationError)(nil),
	}
	file_fold_proto_msgTypes[18].OneofWrappers = []any{}
	file_fold_proto_msgTypes[19].OneofWrappers = []any{}
	file_fold_proto_msgTypes[27].OneofWrappers = []any{}
	file_fold_proto_msgTypes[28].OneofWrappers = []any{}
	file_fold_proto_msgTypes[30].OneofWrappers = []any{}
	file_fold_proto_msgTypes[35].OneofWrappers = []any{}
	file_fold_proto_msgTypes[36].OneofWrappers = []any{}
	file_fold_proto_msgTypes[37].OneofWrappers = []any{}
	file_fold_proto_msgTypes[38].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fold_proto_rawDesc), len(file_fold_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_fold_proto_goTypes,
		DependencyIndexes: file_fold_proto_depIdxs,
		MessageInfos:      file_fold_proto_msgTypes,
	}.Build()
	File_fold_proto = out.File
	file_fold_proto_goTypes = nil
	file_fold_proto_depIdxs = nil
}
