// ABOUTME: Protocol buffer definitions for agent-server communication.
// ABOUTME: Defines the bidirectional streaming protocol for fold control.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: fold.proto

package fold

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from agent to server
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Response
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_fold_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetResponse() *MessageResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterAgent `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Response struct {
	Response *MessageResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Response) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

// Agent registration
type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Unique agent identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // Human-readable name
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`      // What this agent can do
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_fold_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Response to a message request
type MessageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Correlates with SendMessage
	// Types that are valid to be assigned to Event:
	//
	//	*MessageResponse_Thinking
	//	*MessageResponse_Text
	//	*MessageResponse_ToolUse
	//	*MessageResponse_ToolResult
	//	*MessageResponse_Done
	//	*MessageResponse_Error
	//	*MessageResponse_File
	Event         isMessageResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_fold_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{2}
}

func (x *MessageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MessageResponse) GetEvent() isMessageResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MessageResponse) GetThinking() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Thinking); ok {
			return x.Thinking
		}
	}
	return ""
}

func (x *MessageResponse) GetText() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MessageResponse) GetToolUse() *ToolUse {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_ToolUse); ok {
			return x.ToolUse
		}
	}
	return nil
}

func (x *MessageResponse) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *MessageResponse) GetDone() *Done {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *MessageResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *MessageResponse) GetFile() *FileData {
	if x != nil {
		if x, ok := x.Event.(*MessageResponse_File); ok {
			return x.File
		}
	}
	return nil
}

type isMessageResponse_Event interface {
	isMessageResponse_Event()
}

type MessageResponse_Thinking struct {
	Thinking string `protobuf:"bytes,2,opt,name=thinking,proto3,oneof"`
}

type MessageResponse_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type MessageResponse_ToolUse struct {
	ToolUse *ToolUse `protobuf:"bytes,4,opt,name=tool_use,json=toolUse,proto3,oneof"`
}

type MessageResponse_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type MessageResponse_Done struct {
	Done *Done `protobuf:"bytes,6,opt,name=done,proto3,oneof"`
}

type MessageResponse_Error struct {
	Error string `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type MessageResponse_File struct {
	File *FileData `protobuf:"bytes,8,opt,name=file,proto3,oneof"`
}

func (*MessageResponse_Thinking) isMessageResponse_Event() {}

func (*MessageResponse_Text) isMessageResponse_Event() {}

func (*MessageResponse_ToolUse) isMessageResponse_Event() {}

func (*MessageResponse_ToolResult) isMessageResponse_Event() {}

func (*MessageResponse_Done) isMessageResponse_Event() {}

func (*MessageResponse_Error) isMessageResponse_Event() {}

func (*MessageResponse_File) isMessageResponse_Event() {}

type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_fold_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{3}
}

func (x *ToolUse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_fold_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullResponse  string                 `protobuf:"bytes,1,opt,name=full_response,json=fullResponse,proto3" json:"full_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_fold_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{5}
}

func (x *Done) GetFullResponse() string {
	if x != nil {
		return x.FullResponse
	}
	return ""
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_fold_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{6}
}

func (x *FileData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileData) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_fold_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// Messages from server to agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_SendMessage
	//	*ServerMessage_Shutdown
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_fold_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ServerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Payload() {}

func (*ServerMessage_SendMessage) isServerMessage_Payload() {}

func (*ServerMessage_Shutdown) isServerMessage_Payload() {}

// Server acknowledges registration
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Confirmed agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_fold_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{9}
}

func (x *Welcome) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Welcome) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Server tells agent to process a message
type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique request ID for correlation
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // Conversation thread
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`                        // Who sent the message
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                      // Message content
	Attachments   []*FileAttachment      `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_fold_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessage) GetAttachments() []*FileAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type FileAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	mi := &file_fold_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{11}
}

func (x *FileAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileAttachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Server tells agent to shut down
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_fold_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{12}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Binding represents a channel-to-agent mapping for message routing
type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Frontend      string                 `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO-8601
	CreatedBy     *string                `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_fold_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{13}
}

func (x *Binding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Binding) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *Binding) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Binding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Binding) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Binding) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

type ListBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      *string                `protobuf:"bytes,1,opt,name=frontend,proto3,oneof" json:"frontend,omitempty"`
	AgentId       *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsRequest) Reset() {
	*x = ListBindingsRequest{}
	mi := &file_fold_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsRequest) ProtoMessage() {}

func (x *ListBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListBindingsRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{14}
}

func (x *ListBindingsRequest) GetFrontend() string {
	if x != nil && x.Frontend != nil {
		return *x.Frontend
	}
	return ""
}

func (x *ListBindingsRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type ListBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*Binding             `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsResponse) Reset() {
	*x = ListBindingsResponse{}
	mi := &file_fold_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsResponse) ProtoMessage() {}

func (x *ListBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListBindingsResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{15}
}

func (x *ListBindingsResponse) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type CreateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      string                 `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingRequest) Reset() {
	*x = CreateBindingRequest{}
	mi := &file_fold_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingRequest) ProtoMessage() {}

func (x *CreateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{16}
}

func (x *CreateBindingRequest) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *CreateBindingRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateBindingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UpdateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBindingRequest) Reset() {
	*x = UpdateBindingRequest{}
	mi := &file_fold_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindingRequest) ProtoMessage() {}

func (x *UpdateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBindingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingRequest) Reset() {
	*x = DeleteBindingRequest{}
	mi := &file_fold_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingRequest) ProtoMessage() {}

func (x *DeleteBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingResponse) Reset() {
	*x = DeleteBindingResponse{}
	mi := &file_fold_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingResponse) ProtoMessage() {}

func (x *DeleteBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fold_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBindingResponse) Descriptor() ([]byte, []int) {
	return file_fold_proto_rawDescGZIP(), []int{19}
}

var File_fold_proto protoreflect.FileDescriptor

const file_fold_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fold.proto\x12\x04fold\"\xb2\x01\n" +
	"\fAgentMessage\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.fold.RegisterAgentH\x00R\bregister\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x15.fold.MessageResponseH\x00R\bresponse\x12/\n" +
	"\theartbeat\x18\x03 \x01(\v2\x0f.fold.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"b\n" +
	"\rRegisterAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xae\x02\n" +
	"\x0fMessageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\bthinking\x18\x02 \x01(\tH\x00R\bthinking\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x12*\n" +
	"\btool_use\x18\x04 \x01(\v2\r.fold.ToolUseH\x00R\atoolUse\x123\n" +
	"\vtool_result\x18\x05 \x01(\v2\x10.fold.ToolResultH\x00R\n" +
	"toolResult\x12 \n" +
	"\x04done\x18\x06 \x01(\v2\n" +
	".fold.DoneH\x00R\x04done\x12\x16\n" +
	"\x05error\x18\a \x01(\tH\x00R\x05error\x12$\n" +
	"\x04file\x18\b \x01(\v2\x0e.fold.FileDataH\x00R\x04fileB\a\n" +
	"\x05event\"L\n" +
	"\aToolUse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\"O\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"+\n" +
	"\x04Done\x12#\n" +
	"\rfull_response\x18\x01 \x01(\tR\ffullResponse\"W\n" +
	"\bFileData\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xab\x01\n" +
	"\rServerMessage\x12)\n" +
	"\awelcome\x18\x01 \x01(\v2\r.fold.WelcomeH\x00R\awelcome\x126\n" +
	"\fsend_message\x18\x02 \x01(\v2\x11.fold.SendMessageH\x00R\vsendMessage\x12,\n" +
	"\bshutdown\x18\x03 \x01(\v2\x0e.fold.ShutdownH\x00R\bshutdownB\t\n" +
	"\apayload\"A\n" +
	"\aWelcome\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"\xb3\x01\n" +
	"\vSendMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x126\n" +
	"\vattachments\x18\x05 \x03(\v2\x14.fold.FileAttachmentR\vattachments\"]\n" +
	"\x0eFileAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xc1\x01\n" +
	"\aBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfrontend\x18\x02 \x01(\tR\bfrontend\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tH\x00R\tcreatedBy\x88\x01\x01B\r\n" +
	"\v_created_by\"p\n" +
	"\x13ListBindingsRequest\x12\x1f\n" +
	"\bfrontend\x18\x01 \x01(\tH\x00R\bfrontend\x88\x01\x01\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tH\x01R\aagentId\x88\x01\x01B\v\n" +
	"\t_frontendB\v\n" +
	"\t_agent_id\"A\n" +
	"\x14ListBindingsResponse\x12)\n" +
	"\bbindings\x18\x01 \x03(\v2\r.fold.BindingR\bbindings\"l\n" +
	"\x14CreateBindingRequest\x12\x1a\n" +
	"\bfrontend\x18\x01 \x01(\tR\bfrontend\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"A\n" +
	"\x14UpdateBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"&\n" +
	"\x14DeleteBindingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteBindingResponse2I\n" +
	"\vFoldControl\x12:\n" +
	"\vAgentStream\x12\x12.fold.AgentMessage\x1a\x13.fold.ServerMessage(\x010\x012\x97\x02\n" +
	"\fAdminService\x12E\n" +
	"\fListBindings\x12\x19.fold.ListBindingsRequest\x1a\x1a.fold.ListBindingsResponse\x12:\n" +
	"\rCreateBinding\x12\x1a.fold.CreateBindingRequest\x1a\r.fold.Binding\x12:\n" +
	"\rUpdateBinding\x12\x1a.fold.UpdateBindingRequest\x1a\r.fold.Binding\x12H\n" +
	"\rDeleteBinding\x12\x1a.fold.DeleteBindingRequest\x1a\x1b.fold.DeleteBindingResponseb\x06proto3"

var (
	file_fold_proto_rawDescOnce sync.Once
	file_fold_proto_rawDescData []byte
)

func file_fold_proto_rawDescGZIP() []byte {
	file_fold_proto_rawDescOnce.Do(func() {
		file_fold_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fold_proto_rawDesc), len(file_fold_proto_rawDesc)))
	})
	return file_fold_proto_rawDescData
}

var file_fold_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_fold_proto_goTypes = []any{
	(*AgentMessage)(nil),          // 0: fold.AgentMessage
	(*RegisterAgent)(nil),         // 1: fold.RegisterAgent
	(*MessageResponse)(nil),       // 2: fold.MessageResponse
	(*ToolUse)(nil),               // 3: fold.ToolUse
	(*ToolResult)(nil),            // 4: fold.ToolResult
	(*Done)(nil),                  // 5: fold.Done
	(*FileData)(nil),              // 6: fold.FileData
	(*Heartbeat)(nil),             // 7: fold.Heartbeat
	(*ServerMessage)(nil),         // 8: fold.ServerMessage
	(*Welcome)(nil),               // 9: fold.Welcome
	(*SendMessage)(nil),           // 10: fold.SendMessage
	(*FileAttachment)(nil),        // 11: fold.FileAttachment
	(*Shutdown)(nil),              // 12: fold.Shutdown
	(*Binding)(nil),               // 13: fold.Binding
	(*ListBindingsRequest)(nil),   // 14: fold.ListBindingsRequest
	(*ListBindingsResponse)(nil),  // 15: fold.ListBindingsResponse
	(*CreateBindingRequest)(nil),  // 16: fold.CreateBindingRequest
	(*UpdateBindingRequest)(nil),  // 17: fold.UpdateBindingRequest
	(*DeleteBindingRequest)(nil),  // 18: fold.DeleteBindingRequest
	(*DeleteBindingResponse)(nil), // 19: fold.DeleteBindingResponse
}
var file_fold_proto_depIdxs = []int32{
	1,  // 0: fold.AgentMessage.register:type_name -> fold.RegisterAgent
	2,  // 1: fold.AgentMessage.response:type_name -> fold.MessageResponse
	7,  // 2: fold.AgentMessage.heartbeat:type_name -> fold.Heartbeat
	3,  // 3: fold.MessageResponse.tool_use:type_name -> fold.ToolUse
	4,  // 4: fold.MessageResponse.tool_result:type_name -> fold.ToolResult
	5,  // 5: fold.MessageResponse.done:type_name -> fold.Done
	6,  // 6: fold.MessageResponse.file:type_name -> fold.FileData
	9,  // 7: fold.ServerMessage.welcome:type_name -> fold.Welcome
	10, // 8: fold.ServerMessage.send_message:type_name -> fold.SendMessage
	12, // 9: fold.ServerMessage.shutdown:type_name -> fold.Shutdown
	11, // 10: fold.SendMessage.attachments:type_name -> fold.FileAttachment
	13, // 11: fold.ListBindingsResponse.bindings:type_name -> fold.Binding
	0,  // 12: fold.FoldControl.AgentStream:input_type -> fold.AgentMessage
	14, // 13: fold.AdminService.ListBindings:input_type -> fold.ListBindingsRequest
	16, // 14: fold.AdminService.CreateBinding:input_type -> fold.CreateBindingRequest
	17, // 15: fold.AdminService.UpdateBinding:input_type -> fold.UpdateBindingRequest
	18, // 16: fold.AdminService.DeleteBinding:input_type -> fold.DeleteBindingRequest
	8,  // 17: fold.FoldControl.AgentStream:output_type -> fold.ServerMessage
	15, // 18: fold.AdminService.ListBindings:output_type -> fold.ListBindingsResponse
	13, // 19: fold.AdminService.CreateBinding:output_type -> fold.Binding
	13, // 20: fold.AdminService.UpdateBinding:output_type -> fold.Binding
	19, // 21: fold.AdminService.DeleteBinding:output_type -> fold.DeleteBindingResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fold_proto_init() }
func file_fold_proto_init() {
	if File_fold_proto != nil {
		return
	}
	file_fold_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Response)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_fold_proto_msgTypes[2].OneofWrappers = []any{
		(*MessageResponse_Thinking)(nil),
		(*MessageResponse_Text)(nil),
		(*MessageResponse_ToolUse)(nil),
		(*MessageResponse_ToolResult)(nil),
		(*MessageResponse_Done)(nil),
		(*MessageResponse_Error)(nil),
		(*MessageResponse_File)(nil),
	}
	file_fold_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_SendMessage)(nil),
		(*ServerMessage_Shutdown)(nil),
	}
	file_fold_proto_msgTypes[13].OneofWrappers = []any{}
	file_fold_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fold_proto_rawDesc), len(file_fold_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fold_proto_goTypes,
		DependencyIndexes: file_fold_proto_depIdxs,
		MessageInfos:      file_fold_proto_msgTypes,
	}.Build()
	File_fold_proto = out.File
	file_fold_proto_goTypes = nil
	file_fold_proto_depIdxs = nil
}
