<script lang="ts">
  import Card from './Card.svelte';

  interface UsageStats {
    totalInput: number;
    totalOutput: number;
    totalCacheRead: number;
    totalCacheWrite: number;
    totalThinking: number;
    totalTokens: number;
    requestCount: number;
  }

  interface Props {
    stats?: UsageStats;
    csrfToken: string;
  }

  let {
    stats = {
      totalInput: 0,
      totalOutput: 0,
      totalCacheRead: 0,
      totalCacheWrite: 0,
      totalThinking: 0,
      totalTokens: 0,
      requestCount: 0,
    } as UsageStats,
    csrfToken,
  }: Props = $props();

  let loading = $state(false);

  async function refresh() {
    loading = true;
    try {
      const res = await fetch('/api/admin/usage');
      if (res.ok) {
        stats = await res.json();
      }
    } finally {
      loading = false;
    }
  }

  function formatNumber(n: number): string {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(1) + 'K';
    return n.toString();
  }

  const statCards: { label: string; key: keyof UsageStats; subtitle: string }[] = [
    { label: 'Total Tokens', key: 'totalTokens', subtitle: 'Input + Output' },
    { label: 'Input', key: 'totalInput', subtitle: 'Prompt tokens' },
    { label: 'Output', key: 'totalOutput', subtitle: 'Response tokens' },
    { label: 'Cache Read', key: 'totalCacheRead', subtitle: 'From cache' },
    { label: 'Cache Write', key: 'totalCacheWrite', subtitle: 'Written to cache' },
    { label: 'Thinking', key: 'totalThinking', subtitle: 'Reasoning' },
    { label: 'Requests', key: 'requestCount', subtitle: 'Total calls' },
  ];
</script>

<div data-testid="usage-page" class="space-y-6">
  <!-- Page Header -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
    <div>
      <h2 class="text-2xl font-[var(--typography-fontWeight-bold)] text-fg">Token Usage Analytics</h2>
      <p class="text-[length:var(--typography-fontSize-sm)] text-fgMuted mt-1">Monitor LLM token consumption across your agents.</p>
    </div>
    <button
      type="button"
      class="text-[length:var(--typography-fontSize-sm)] text-fgMuted hover:text-fg"
      onclick={refresh}
      disabled={loading}
    >
      {loading ? 'Refreshing...' : 'Refresh'}
    </button>
  </div>

  <!-- Stats Grid -->
  <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
    {#each statCards as card (card.key)}
      <Card>
        {#snippet children()}
          <div class="p-5">
            <p class="text-[length:var(--typography-fontSize-xs)] text-fgMuted uppercase tracking-wide mb-2">{card.label}</p>
            <p class="text-2xl font-[var(--typography-fontWeight-bold)] text-fg">{formatNumber(stats[card.key])}</p>
            <p class="text-[length:var(--typography-fontSize-xs)] text-fgMuted mt-1">{card.subtitle}</p>
          </div>
        {/snippet}
      </Card>
    {/each}
  </div>

  <!-- Info Panel -->
  <Card>
    {#snippet children()}
      <div class="p-6">
        <h3 class="font-[var(--typography-fontWeight-semibold)] text-fg mb-2">About Token Usage</h3>
        <p class="text-[length:var(--typography-fontSize-sm)] text-fgMuted mb-3">
          Token usage is tracked for each agent request and includes:
        </p>
        <ul class="text-[length:var(--typography-fontSize-sm)] text-fgMuted space-y-1 list-disc list-inside">
          <li><strong class="text-fg">Input tokens:</strong> Tokens sent to the model (your prompts)</li>
          <li><strong class="text-fg">Output tokens:</strong> Tokens generated by the model (responses)</li>
          <li><strong class="text-fg">Cache read tokens:</strong> Tokens served from prompt cache (cost reduction)</li>
          <li><strong class="text-fg">Cache write tokens:</strong> Tokens written to prompt cache</li>
          <li><strong class="text-fg">Thinking tokens:</strong> Internal reasoning tokens (extended thinking models)</li>
        </ul>
      </div>
    {/snippet}
  </Card>
</div>
